### ISSUE TITLE
Make project compilation the common build, test, and check workflow

### ISSUE THREAD

**Issue by ppanko** [ppanko/dotfiles#47]
## Goal

Provide one predictable project-level build/test/check workflow across languages by leaning on built-in `project.el` and Emacs compilation mode instead of creating a new task-runner abstraction.

The intended result is simple: from any project buffer, run the project's normal verification command, re-run it quickly, and navigate failures using the standard compilation interface.

## Current gap

The configuration already has strong language-specific execution paths:

- ESS and `targets` for R;
- Python REPL and Eglot integration;
- a simple C++ `compile-command` hook;
- generic `compile` is bound globally.

What is missing is a common project-level convention for ordinary repository commands such as tests, checks, builds, linters, or project-specific verification scripts. Today that knowledge is largely outside the shared project layer.

## Scope

Use `project.el` plus compilation mode as the common execution boundary.

At minimum:

- expose an ergonomic project command that runs the current project's configured `compile-command` from the project root;
- prefer built-in `project-compile` / compilation behavior where it already provides the needed semantics;
- make `recompile` an obvious part of the workflow so the last project command can be repeated cheaply;
- preserve standard `next-error` / previous-error navigation into source files;
- allow repositories to define their own normal command through ordinary Emacs project-local configuration, especially `.dir-locals.el` / `compile-command`;
- ensure a command launched from a project buffer executes with the intended project root as its working directory;
- give each project its own compilation/check buffer identity so checks in different project tabs can coexist without clobbering each other;
- treat that buffer as project-scoped, not language-scoped: one project may contain multiple languages while still having one canonical repository-level verification command;
- keep compilation buffers usable alongside the native project-tab workflow established by #29;
- preserve language-specific workflows where they are more appropriate, such as interactive ESS evaluation or Python REPL use.

Do not teach P3 the semantics of npm, pytest, R CMD check, `targets`, Make, Cargo, or other individual build systems. The repository owns the command; Emacs owns execution and error navigation.

## Mixed-language projects

A project's canonical verification command may orchestrate multiple languages or toolchains. For example, an R/Python repository might use `make check`, a repository script, or another project-owned command that runs both R and Python verification steps.

P3 should treat that orchestration as one repository-level command. It must not split checks into language-specific compilation tasks or model their constituent steps itself.

Language-specific interactive workflows remain separate. ESS still owns interactive R development; Python REPL/Eglot still own interactive Python development. The project check answers the higher-level question: does this repository pass its normal verification step?

## Project-local configuration

Project-specific command selection should use existing Emacs mechanisms rather than a new P3 task registry.

A project should be able to define, for example, its preferred verification command through a safe `.dir-locals.el` setting for `compile-command`. P3 may provide documentation or a small helper for discovering/running that command, but should not maintain a second per-project command database.

If a project has no configured command, fall back to ordinary `project-compile` / `compile` prompting rather than guessing based on repository contents.

## Compilation-buffer behavior

Compilation output should remain ordinary compilation-mode output, but concurrent project work should not force unrelated repositories into the same shared `*compilation*` buffer.

Use a lightweight project-derived buffer identity, such as `*compilation: PROJECT*`, or the nearest native equivalent. This is only a naming/integration concern; do not introduce a process registry, task identity system, or language-specific compilation buffers.

Within a single project, the canonical project check remains one repository-level compilation workflow even when that command internally invokes multiple languages or tools.

## Failure behavior

- A missing project root should fail clearly before launching a process.
- A missing executable or failed command should remain an ordinary compilation failure with visible output.
- Malformed project-local command configuration should not prevent Emacs from opening or using the project.
- Cancellation/termination should use normal compilation/process behavior.

## Non-goals

- Do not build a generalized task runner, command palette, Make replacement, or CI orchestrator.
- Do not auto-detect and execute arbitrary repository scripts.
- Do not duplicate `targets`, ESS, Eglot, pytest tooling, or other language-specific interfaces.
- Do not create a project-specific process/session database.
- Do not create separate R/Python/etc. project-check abstractions for mixed-language repositories.
- Do not add persistent background jobs or a job scheduler.
- Do not require every repository to adopt `.dir-locals.el` if ordinary prompting is sufficient.

## Acceptance criteria

- [ ] From a project buffer, one clear command runs the project's configured compilation/check command from the project root.
- [ ] The implementation reuses built-in `project.el` and compilation mode rather than creating a parallel task system.
- [ ] The last command can be repeated through normal `recompile` behavior.
- [ ] Compilation errors remain navigable through standard `next-error` behavior.
- [ ] Project-specific commands can be supplied through ordinary Emacs local configuration such as `.dir-locals.el` / `compile-command`.
- [ ] When no project-specific command is configured, the user is prompted rather than the config guessing a toolchain.
- [ ] Different projects can keep independent compilation/check buffers so concurrent checks do not overwrite one another's output.
- [ ] A mixed-language repository can define one canonical verification command that orchestrates multiple toolchains without P3 modeling those tools separately.
- [ ] Existing ESS/`targets`, Python REPL/Eglot, and other language-specific workflows remain intact.
- [ ] The workflow operates coherently inside the project tabs introduced by #29 without adding another workspace/process model.
- [ ] No task registry, build-system abstraction, command-detection framework, language-specific project-check abstraction, or CI layer is introduced.
- [ ] Focused ERT coverage verifies project-root execution, project-specific compilation-buffer behavior, and P3-owned command behavior without testing compilation-mode internals.
